version: "3.8"

volumes: 

services: 

    rabbitmq:
        image: 

    logger:   
        image:  
        
    elk:
        image: 
        ports: 
            - "5601:5601" #kibana
            - "9200:9200" #elastic
            - "5044:5044" #logstash

    