version: "3.8"

services: 
    postgres:
        image: postgres:9.6.19-alpine
        container_name: postgres_container
        volumes: 
            - /home/and1helicopter/program/project/docker/volumes/PostgresDB:/var/lib/postgresql/data
        environment: 
            POSTGRES_USER: user
            POSTGRES_PASSWORD: user
            POSTGRES_DB: AeroDB
        ports: 
            - 5432:5432
        # networks:
        #     - net_logger

    redis:
        image: redis:alpine3.12
        container_name: redis_container
        # volumes:
        # environment: 
        ports:
            - 6379:6379
        # networks:
        #     - net_logger

    rabbitmq:
        image: rabbitmq:3.8.9-management-alpine
        container_name: rabbitmq_container
        # volumes: 
        #     - ./.rabbitmq/etc/:/etc/rabbitmq/
        #     - ./.rabbitmq/data/:/var/lib/rabbitmq/
        #     - ./.rabbitmq/logs/:/var/log/rabbitmq/
        environment: 
        #     RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
        #     RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
        #     RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
            RABBITMQ_DEFAULT_USER: user
            RABBITMQ_DEFAULT_PASS: password
        ports:
            - 5672:5672
            - 15672:15672
        # networks:
        #     - net_logger  

    elasticsearch: 
        image: elasticsearch:7.9.3
        container_name: elastic_container
        environment:
            - xpack.security.enabled=false
            - discovery.type=single-node
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        volumes: 
            - /home/and1helicopter/program/project/docker/volumes/DataElastic:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
        # networks:
        #     - net_logger

    kibana:
        image: kibana:7.9.3
        container_name: kibana_container
        environment:
            - ELASTICSEARCH_HOSTS=http://elastic_container:9200
        ports:
            - 5601:5601
        depends_on: 
            - elasticsearch
        # networks:
        #     - net_logger

# volumes: 
#     data_elastic:
#         driver: local

# networks: 
#     net_logger:
#         driver: bridge